import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>project scale mkII</title>
        <meta name="description" content="Create ambitions and grow. Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-900 text-white">
        Test
      </main>
    </>
  );
};

export default Home;
